import { AnimatePresence, motion } from 'framer-motion';
import { Bookmark, ChevronDown, ChevronRight, FileText, Filter, Flame, Search } from 'lucide-react';
import { useMemo } from 'react';
import { Badge, Button, Card, IconButton, Input, ProgressBar, SegmentedToggle } from './ui';
import { calculateProgress, statusForTopic } from '../lib/progress';
import { useProgressStore } from '../store/progressStore';
import { useSyllabusStore } from '../store/syllabusStore';
import type { Topic } from '../types';

function matches(topic: Topic, query: string): boolean { return !query || topic.title_en.toLowerCase().includes(query.toLowerCase()) || topic.title_hi.includes(query) || topic.children.some((child) => matches(child, query)); }
function TopicRow({ topic, depth = 0 }: { topic: Topic; depth?: number }) {
  const { expanded, toggleExpanded, selectedTopic, selectTopic, toggleCompletion, searchQuery } = useSyllabusStore();
  const statusMap = useProgressStore((s) => s.statusMap);
  if (!matches(topic, searchQuery)) return null;
  const open = expanded[topic.id] || Boolean(searchQuery && topic.children.some((c) => matches(c, searchQuery)));
  const status = statusForTopic(topic, statusMap);
  return <div><div role="treeitem" tabIndex={0} aria-expanded={topic.children.length ? open : undefined} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') selectTopic(topic.id); if (e.key === 'ArrowRight' && topic.children.length && !open) toggleExpanded(topic.id); if (e.key === 'ArrowLeft' && open) toggleExpanded(topic.id); }} onClick={() => selectTopic(topic.id)} className={`group flex cursor-pointer items-center gap-2 rounded-[14px] px-2 py-2.5 text-sm transition hover:bg-violet-50 ${selectedTopic === topic.id ? 'bg-violet-50 text-primary' : 'text-slate-600'}`} style={{ marginLeft: depth * 14 }}><button aria-label={open ? 'Collapse topic' : 'Expand topic'} onClick={(e) => { e.stopPropagation(); if (topic.children.length) toggleExpanded(topic.id); }} className="text-slate-300">{topic.children.length ? (open ? <ChevronDown size={15} /> : <ChevronRight size={15} />) : <span className="w-[15px]" />}</button><input type="checkbox" aria-label={`Mark ${topic.title_en} complete`} checked={topic.completed || status === 'completed' || status === 'mastered'} onChange={(e) => { e.stopPropagation(); toggleCompletion(topic.id, e.target.checked); }} onClick={(e) => e.stopPropagation()} className="h-4 w-4 rounded border-slate-200 text-primary focus:ring-primary" /><div className="min-w-0 flex-1"><p className="truncate font-medium">{topic.title_en}</p><p className="truncate text-[10px] text-slate-400">{topic.title_hi}</p></div>{status !== 'not_started' && <Badge tone={status === 'completed' || status === 'mastered' ? 'green' : status === 'revision_due' ? 'amber' : 'purple'}>{status === 'completed' ? 'Done' : status === 'learning' ? 'In Progress' : status.replace('_', ' ')}</Badge>}{topic.notes && <FileText size={13} className="text-slate-300" />}{topic.bookmarked && <Bookmark size={13} className="text-amber-400" />}{topic.revision && <Flame size={13} className="text-orange-400" />}</div><AnimatePresence initial={false}>{open && topic.children.length > 0 && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">{topic.children.map((child) => <TopicRow key={child.id} topic={child} depth={depth + 1} />)}</motion.div>}</AnimatePresence></div>;
}
export function SyllabusExplorer() {
  const { exams, selectedExam, setExam, searchQuery, setSearchQuery } = useSyllabusStore();
  const syllabus = exams[selectedExam];
  const progress = useMemo(() => calculateProgress(syllabus.subjects.flatMap((subject) => subject.topics)), [syllabus]);
  return <Card className="flex h-full min-h-0 flex-col p-5"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Syllabus Explorer</p><h2 className="mt-1 text-xl font-bold text-slate-800">Your customized study path</h2></div><SegmentedToggle options={['RAS Pre', '2nd Science', '2nd GK']} value={selectedExam} onChange={setExam} /><div className="mt-4 flex gap-2"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3.5 text-slate-400" /><Input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search topics..." className="w-full pl-9" /></div><IconButton label="Filter topics"><Filter size={18} /></IconButton></div><div className="mt-4 rounded-[18px] bg-violet-50 p-4"><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-600">Overall Progress</span><span className="text-xl font-bold text-primary">{progress.percentage}%</span></div><ProgressBar value={progress.percentage} /><p className="mt-2 text-xs text-slate-400">{progress.completedLeaves} / {progress.totalLeaves} Topics Completed</p><Button className="mt-3 w-full bg-white !text-primary shadow-none hover:bg-violet-100">View Analytics</Button></div><div role="tree" aria-label="Syllabus topics" className="mt-5 min-h-0 flex-1 space-y-1 overflow-y-auto pr-1">{syllabus.subjects.map((subject, index) => <SubjectRow key={subject.id} subject={subject} index={index} />)}</div></Card>;
}
function SubjectRow({ subject, index }: { subject: { id: string; title_en: string; title_hi: string; topics: Topic[] }; index: number }) {
  const { expanded, toggleExpanded, searchQuery } = useSyllabusStore();
  const open = expanded[subject.id] || Boolean(searchQuery && subject.topics.some((topic) => matches(topic, searchQuery)));
  return <div><button onClick={() => toggleExpanded(subject.id)} aria-expanded={open} className="flex w-full items-center gap-2 rounded-[14px] px-2 py-3 text-left text-sm font-bold text-slate-700 hover:bg-slate-50"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-violet-50 text-[10px] text-primary">{String(index + 1).padStart(2, '0')}</span><span className="min-w-0 flex-1 truncate">{subject.title_en}</span><span className="text-[10px] text-slate-400">{subject.topics.length}</span>{open ? <ChevronDown size={15} /> : <ChevronRight size={15} />}</button><AnimatePresence>{open && <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden">{subject.topics.map((topic) => <TopicRow key={topic.id} topic={topic} />)}</motion.div>}</AnimatePresence></div>;
}
