import { motion } from 'framer-motion';
import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode } from 'react';
export function Card({ children, className = '', ...props }: { children: ReactNode; className?: string } & React.HTMLAttributes<HTMLDivElement>) {
  return <div className={`rounded-card bg-surface shadow-soft transition-transform duration-200 hover:-translate-y-0.5 ${className}`} {...props}>{children}</div>;
}
export function Button({ children, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`rounded-[16px] bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-soft-purple transition hover:bg-violet-600 focus:outline-none focus:ring-2 focus:ring-primary/40 ${className}`} {...props}>{children}</button>; }
export function IconButton({ children, label, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) { return <button aria-label={label} className={`rounded-[14px] p-2 text-slate-500 transition hover:bg-violet-50 hover:text-primary focus:outline-none focus:ring-2 focus:ring-primary/40 ${className}`} {...props}>{children}</button>; }
export function Input({ className = '', ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={`rounded-[16px] border-0 bg-slate-50 px-4 py-3 text-sm text-slate-800 outline-none ring-1 ring-slate-100 transition placeholder:text-slate-400 focus:ring-2 focus:ring-primary/40 ${className}`} {...props} />; }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'purple' | 'green' | 'amber' }) { const tones = { neutral: 'bg-slate-100 text-slate-500', purple: 'bg-violet-50 text-primary', green: 'bg-green-50 text-green-600', amber: 'bg-amber-50 text-amber-600' }; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${tones[tone]}`}>{children}</span>; }
export function ProgressBar({ value }: { value: number }) { return <div className="h-2 overflow-hidden rounded-full bg-violet-100"><motion.div initial={{ width: 0 }} animate={{ width: `${value}%` }} transition={{ duration: .7 }} className="h-full rounded-full bg-primary" /></div>; }
export function SegmentedToggle({ options, value, onChange }: { options: string[]; value: number; onChange: (index: number) => void }) { return <div className="flex rounded-[16px] bg-slate-100 p-1">{options.map((option, index) => <button key={option} onClick={() => onChange(index)} aria-pressed={value === index} className={`flex-1 rounded-[12px] px-2 py-2 text-xs font-semibold transition ${value === index ? 'bg-white text-primary shadow-sm' : 'text-slate-400 hover:text-slate-600'}`}>{option}</button>)}</div>; }
export function EmptyState({ icon, title, description }: { icon: ReactNode; title: string; description: string }) { return <div className="flex h-full min-h-[260px] flex-col items-center justify-center text-center"><div className="mb-4 rounded-[20px] bg-violet-50 p-4 text-primary">{icon}</div><h3 className="text-lg font-bold text-slate-800">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-400">{description}</p></div>; }
